### ISSUE TITLE
very long time series, performance drop

### ISSUE THREAD

**Issue by aappaappoo** [gzerveas/mvts_transformer#13]
implied in the text,who combine the triplet loss with a deep causal
CNN with dilation, in order to make the method effective for very long time series. Is there any relevant code to refer to?This method does not seem to work well on a time series dataset with a sequence length of 5000 and a feature number of 2.

**Comment by gzerveas** [comment]
The quick existing solution when handling very long time series is to use `--subsample_factor k` to keep every kth sample.
However, although definitely helping with compute times, it doesn't always yield good accuracies (although sometimes it might). Especially for very low-dimensional time series (dim=2 in your case), this is a known limitation. A promising solution, as you mentioned, is using CNN layer(s) on top of the raw input sequence. However, this code is not implemented in this repo. You are welcome to implement it and submit a pull request.
