### ISSUE TITLE
Something wrong when training from scratch

### ISSUE THREAD

**Issue by xiqxin1** [gzerveas/mvts_transformer#21]
Hello

I want to pre-train the model from the very beginning using your data. I've tried your classification command, but many bugs occur. 

Does anyone successfully run the code from scratch?

BTW, how to perform mask in the code?

**Comment by gzerveas** [comment]
Hi, you have to be very specific with respect to what command you are running and what errors you are getting. A lot of people have successfully run the code from scratch, some getting better numbers than mine :) My answer about masking is in the thread of the separate Issue you have opened.

**Comment by xiqxin1** [comment]
Thanks a lot, I think the dataset in the classification task does not match, but for the regression task it is fine. Thank you!
