### ISSUE TITLE
what's the right way to calculate predicted value and extract the representation?

### ISSUE THREAD

**Issue by superfan123** [gzerveas/mvts_transformer#25]
Hi George,
Great project. This really open a new way for MTS analysis.
I have run your code and everything looks good and very fast. When I tried to use the model to calculate the prediction, the value can't match the results in "predictions" folder.
So what I did is load the check points, load the best model, then use first row in "predictions" targets.npy to feed into the model and compare the output with first row in predictions.npy . padding_masks = torch.BoolTensor([[1]]) . My results can't match the prediction output from yours. could you share some idea how to do this on a record by record base?
Another question is how to extract the encoder value, for example I have PM25 data 24 by 9 dataframe, How to get the corresponding 24 by 128 representation data frame? As once this step done I can use the new dataframe for other models input and don't need to calculate these values on the fly to save some time?
Thank you in advance.

**Comment by gzerveas** [comment]
Hi, thank you for the kind words.
- Can you please write the commands you are using for your experiments, and what you are comparing with and trying to match?
- I describe a way of extracting the final latent representations [here](https://github.com/gzerveas/mvts_transformer/issues/14#issuecomment-1136463129). I hope that is what you are looking for.
