### ISSUE TITLE
DummyTSTransformerEncoder

### ISSUE THREAD

**Issue by Hoozits728** [gzerveas/mvts_transformer#4]
Are you missing this class in ts_transformer.py along with DummyTSTransformerEncoderClassiregressor?

**Comment by gzerveas** [comment]
The Dummy* classes in the code were simply a linear model, not a transformer, and I used them for debugging when developing the code. I simply forgot to remove them from the function where the user chooses the model. You can either delete that part or ignore it; either way, you are not missing out on anything. At some point I will push a commit erasing them :)

**Comment by Hoozits728** [comment]
Thank you for getting back to me. I've really been enjoying studying your paper and code these past few months. I find this to be a valuable contribution.

**Comment by gzerveas** [comment]
Thank you very much for the kind words. I glad you found it useful :)
