### ISSUE TITLE
how should mat file containing ECG data be feed to this model?? could anyone help on this??

### ISSUE THREAD

**Issue by Shubhamsg17** [gzerveas/mvts_transformer#43]

**Comment by gzerveas** [comment]
You should basically use a package that reads the `.mat` file format into a python data structure, and then have a look at the example [here](https://github.com/gzerveas/mvts_transformer/blob/master/example_data_class.py) to see how you should convert it into a Pandas dataframe used by the dataloader.

One example for loading `.mat` using `scipy`:
```python
import scipy.io
mat = scipy.io.loadmat('file.mat')
```

**Comment by Shubhamsg17** [comment]
thanks for the reply. ill try converting to dataframe and pass this dataframe to the model
