### ISSUE TITLE
failsafe_requirements.txt missing

### ISSUE THREAD

**Issue by mariomorvan** [gzerveas/mvts_transformer#5]
Hello, the file `failsafe_requirements.txt` mentioned in README does not seem to be present in the repo? 

When installing the package from a new conda environment, I just had to downgrade python to 3.8 to avoid sktime installation issues, and it now seems to work.

**Comment by gzerveas** [comment]
Thanks for reminding me, and for your feedback! I have added the file and included your feedback in the README.
