### ISSUE TITLE
current issue on loading the dataset

### ISSUE THREAD

**Issue by harrykwon0524** [gzerveas/mvts_transformer#60]
Hello, i am currently new to this code so I am trying to run the classification using the custom dataset of my own. Although I have the data file in the folder, the exception keeps saying there is no file existing. Can anyone see why this is such a case? I will upload the screenshots for better understanding. Any advice would be appreciated. Thank you
<img width="606" alt="file_directory" src="https://github.com/gzerveas/mvts_transformer/assets/77919172/e282a62b-c7b7-4f05-950f-19717f0685a8">
<img width="620" alt="datasource_error" src="https://github.com/gzerveas/mvts_transformer/assets/77919172/e6ff75e2-b9f2-4d6c-b2e0-180a6256769a">

**Comment by gzerveas** [comment]
Hi,

Looks to me that the reason is that your specified directory is using a slash here: `classification/` , while you are on Windows and paths should use backslashes `\`. 

Having said that, the code has not been tested on Windows,  so I am really not sure whether you will face more difficulties in the future. I recommend using Windows Subsystem for Linux,  it's very easy to install and use.

**Comment by harrykwon0524** [comment]
Hi thanks for the response. I found a linux based environment to run the program and installed the virtualenv and requirements. but i still keep getting error from tqdm, saying that there is no module. I used pip install tqdm and pip3 install tqdm. How can i solve this issue

**Comment by gzerveas** [comment]
Okay, I would say that this is not an issue with loading the dataset, or this repository, it is environment/Python debugging.

Can you show a screenshot or paste what kind of error you are getting?
Also, can you simply start a python shell within your virtual environment and see whether you can import tqdm?

**Comment by harrykwon0524** [comment]
<img width="1230" alt="33" src="https://github.com/gzerveas/mvts_transformer/assets/77919172/d8f38e63-f014-478c-83c9-0cf48479c556">
<img width="734" alt="2" src="https://github.com/gzerveas/mvts_transformer/assets/77919172/36175437-6ed0-4423-8b57-f8b106ca4831">
<img width="1268" alt="스크린샷 2023-11-06 231322" src="https://github.com/gzerveas/mvts_transformer/assets/77919172/bb98a8fa-ff4f-48cc-8b24-bfc2673b151d">
this is currently the status
